apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx" # Nginx Ingress Controller'ı kullanıyor
spec:
  rules:
  - http:
      paths:
      - path: /backend # Backend için URI prefix
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 3000
      - path: / # Diğer tüm istekler için
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
